<div class="page-header">
    <h1>
        Auditorias del Sistema 
        <small>Usuario: <?php eh(strtoupper($usuario->login)) ?></small>
    </h1>
</div>   
    <?php View::content() ?>
<div id="scaffold">
    <?php
    $dt = new DataTable($auditorias);
    $dt->addHeaders('Fecha y Hora', 'Acción','Tipo','Descripción','IP Usuario');
    $dt->addFields('fecha_at', 'accion', 'tipo','detalles', 'ip');
    $dt->url($url);
    echo $dt->render('class="table table-bordered table-hover table-condensed"');
    ?>
</div>