<div class="page-header">
    <h1><?php eh($titulo) ?></h1>
</div>
<div class="row">
    <div class="span3">
        <?php View::partial('backend/menus/roles') ?>
    </div>
    <div class="span8 span-derecho" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php //echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php echo Form::hidden('rol.id') ?>
        <div class="control-group">
            <label class="control-label" for="rol_rol">Nombre del rol* : </label>
            <div class="controls">
                <?php echo Form::text('rol.rol') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="rol_plantilla">Plantilla a Usar : </label>
            <div class="controls">
                <?php echo Form::text('rol.plantilla') ?>
            </div>
        </div>

        <div class="form-actions btn-group">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
        </div>
        <?php echo Form::close() ?>
    </div>
</div>

