<div class="page-header">
    <h1>Roles (Perfiles) del Sistema</h1>
</div>
<?php View::content() ?>
<?php
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Rol'));
$dt = new DataTable($roles);
$dt->addHeaders('id', 'Rol', 'plantilla a usar', 'Editar', 'Eliminar');
$dt->addFields('id', 'rol', 'plantilla');
$dt->link('admin/roles/editar', '<span class="btn btn-warning"><i class="icon-edit icon-white" title="Activar"></i></span>');
$dt->linkConfirm('admin/roles/eliminar', '<span class="btn btn-danger"><i class="icon-trash icon-white" title="Activar"></i></span>');
echo $dt->render('class="table table-bordered table-hover table-condensed"');
?>
