{% block prebuttons%}
{% endblock %}

{%buffer  view%}view/{{item.id}}{%endbuffer%}
{%exec Html::linkAction view, '<i class="fa fa-eye"></i>',  'class="btn btn-info"' %}

{%buffer  view%}edit/{{item.id}}{%endbuffer%}
{%exec Html::linkAction view, '<i class="fa fa-pencil"></i>',  'class="btn btn-warning"' %}

{%buffer  view%}delete/{{item.id}}{%endbuffer%}
{%exec Html::linkAction view, '<i class="fa fa-trash"></i>',  'class="btn btn-danger" data-msg="¿Desea Eliminar?"' %}

{% block postbuttons%}
{% endblock %}