{% if result.count %}
	<form>
	{% set all =  f.getArgs %}
	{% for i,j in all %}
		<input name="{{i}}" value="{{j}}" type="hidden"/>
	{% endfor %}
	<label class="col-2 control">Filtrar por:</label>
	<div class="col-4">
	<select name="col" class="control">
	{%for value in header %}
		<option value="{{value}}">{{value | capfirst}}</option>
	{%endfor%}
	</select>
	</div>
	<div class="col-4">
		<input name="val" class="control" type="text" />
	</div>
	<button type="submit" class="btn btn-success">Aceptar</button>
	</form>
	<table class="{%block cssclass%}t bordered condensed hover{% endblock %}">
		<thead>
			{%for value in header %}
				{%def t%}{"order": "{{value}}" }{%enddef%} 
				{%buffer url%}{{href}}{%exec f.getURL t%}{%endbuffer%}
				{%buffer label%}{{value | capfirst}} <i class="fa fa-sort"></i>{%endbuffer%}
				<th>{%exec Html::linkAction url, label %} </th>
			{%endfor%}
			{% if action %}
				<th>Acciones</th>
			{% endif %}
		</thead>

	{%for item in result%}  
		<tr>
			{% for key, val in item %}
				<td>{%exec grid.getCol key, val %}</td>
			{% endfor %}

			{% if action %}
				<td>
				{% partial action item  %}
				</td>
			{% endif %}
		</tr>
	{%endfor%}
	</table>
	{%autoescape off%}{{result}}{%endautoescape%}
{%else%}
	<div class="alert alert-info">No hay datos para mostrar</div>
{%endif%}
