<div class="page-header">
    <h1><?php eh($title) ?></h1>
</div>
<div class="row">
    <div class="span6 offset3">
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php echo Form::hidden('resource.id') ?>
        <div class="row">
            <div class="span2">
                <label for="recurso_modulo">Modulo : </label>
            </div>
            <div class="span2">
                <label for="recurso_controlador">Controlador * :</label>
            </div>
            <div class="span2">
                <label for="recurso_accion">Accion  : </label>
            </div>
        </div>
        <div class="row control-group">
            <div class="span2">
                <?php echo Form::text('resource.module', 'class="span2"') ?>
            </div>
            <div class="span2">
                <?php echo Form::text('resource.controller', 'class="span2"') ?>
            </div>
            <div class="span2">
                <?php echo Form::text('resource.action', 'class="span2"') ?>
            </div>
        </div>
        <div class="control-group">
            <div class="control-group">
                <label class="control-label" for="menus_activo">Activo: </label>
            <?php echo Form::select('resource.activo', array('1' => 'Si', '0' => 'No')) ?>
            </div>
            <?php View::partial('backend/submit')?>
        <?php echo Form::close() ?>
    </div>
</div>
