<div class="page-header">
    <h1>Crear una Cuenta</h1>
</div>
<?php View::content(); ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('registro.id') ?>
<div class="control-group">
    <label for="usuario_login">Nombre de Usuario (Login)* : </label>
    <div class="controls">
        <?php echo Form::text('registro.login') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave">Contrase&ntilde;a* : </label>
    <div class="controls">
        <?php echo Form::pass('registro.clave') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave2">Repita Contrase&ntilde;a* : </label>
    <div class="controls">
        <?php echo Form::pass('registro.clave2') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_email">Correo Electronico* : </label>
    <div class="controls">
        <?php echo Form::text('registro.email') ?>
    </div>
</div>
<?php View::partial('backend/submit')?>
<?php echo Form::close() ?>