{% extends 'default.phtml'%}
{%block title%}Configurando <em>{{config}}</em>{%endblock%}
{%block content%}
    <div class="offset-3 col-6" >
        {%exec View::content %}
        {%exec Form::open '', 'post'%}
        {%for key, val in values%}
            <fieldset>
                <legend><?php echo $key ?></legend>
                {%for  name, value in val %}
                    <label class="col-4 control-label" for="config_name">{{name|Title}}: </label>
                     {%buffer name%}config.{{key}}.{{name}}{%endbuffer%}
                    {% if value == "On" OR value == 'Off'%}
                        {%set check = (value == 'On')%}
                        {%exec Form::check name, 1, 'class="control"', check %}
                    {%else%}
                        {%exec Form::text name, 'class="control"', value %}
                    {%endif%}
                {%endfor%}
            </fieldset>
        {%endfor%}
        {%inline '_shared/submit.phtml'%}
        </form>
    </div>
</div>
{%endblock%}