
<div class="page-header">
    <h1>Privilegios para <em><?php echo $rol->rol; ?></em></h1>
</div>
<?php View::content() ?>
<?php if (isset($results)) : ?>
    <?php echo Form::open('admin/privilegios/asignar_privilegios/') ?>
    <?php View::partial('backend/submit') ?>
    <?php echo Form::hidden("rol", null, $rol->id) ?>
    <table id="tabla_privilegios" class="table table-bordered table-condensed table-hover">
        <thead>
            <tr>
                <th>Recursos</th>
                <th>Descripcion</th>
                <th>Asignar</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($results->items as $item) : ?>
                <tr>
                    <td><?php eh($item->recurso) ?></td>
                    <td><?php eh($item->descripcion) ?></td>
                    <td><?php echo Form::check("priv.", $item->id, NULL, in_array($item->id, $privilegios)) ?>
                        <?php echo Form::hidden("todo.", null, $item->id) ?>
                    </td>

                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php View::partial('paginators/bootstrap', false, array('page' => $results, 'url' => Router::get('controller_path') . '/index')); ?>

<?php else : // Si no hay items?>
    <h2>No hay ningún registro</h2>
<?php endif ?>
<?php echo Form::close() ?>
