<?php $url = 'http://' .$_SERVER['SERVER_NAME'] . PUBLIC_PATH. "register/active/{$user->id}/{$hash}";?>
Felicidades tu cuenta en <strong><?php echo Config::get('backend.app.nombre');?></strong> ha sido creada Exitosamente 
<ul>
    <li>Usuario:  <strong><?php echo $user->login?></strong></li>
    <li>Contraseña: <strong><?php echo $clave?></strong></li>
</ul>
<p>Para activar tu cuenta visita el siguiente link:
<a href="<?php echo $url;?>"><?php echo $url;?></a></p>
