<?php
/**
 * KumbiaPHP web & app Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://wiki.kumbiaphp.com/Licencia
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@kumbiaphp.com so we can send you a copy immediately.
 *
 * Paginador "punbb" para aplicaciones
 *
 * Parametros del paginador:
 *   page: objeto obtenido al invocar al paginador
 *   show: numero de paginas que se mostraran en el paginador
 *   url: url para la accion que efectua la paginacion, por defecto "module/controller/page/"
 *        y se envia por parametro el numero de pagina
 *
 * @category   Kumbia
 * @package    Partials
 * @copyright  Copyright (c) 2005-2010 Kumbia Team (http://www.kumbiaphp.com)
 * @license    http://wiki.kumbiaphp.com/Licencia     New BSD License
 */
if (!isset($url)) {
    extract(Router::get(), 0);
    $url = "$controller/$action";
    if ($module) {
        $url = "$module/$url";
    }
}

if (!isset($show)) {
    $show = 10;
}

$half = floor($show / 2);

//Calculando el inicio de paginador centrado
if ($page->current <= $half) {
    $start = 1;
}elseif (($page->total - $page->current) < $half) {
    $start = $page->total - $show + 1;
    if ($start < 1)
        $start = 1;
} else {
    $start = $page->current - $half;
}

$filter = \KBackend\Libs\FilterSQL::get();
?>

<?php if($page->total != 1):?>
<div class="text-center">
	<ul class="pagination">
		<?php
		/*Page Prev*/
		if ($page->prev) {
			$href = $url. $filter->getURL(array('page' => $page->prev));
			echo '<li class="prev">', Html::link($href, 'Anterior', 'title="Ir a la pág. anterior"'), '</li>'; // Se coloca el link sin numero de pagina para la pagina 1
		} else {
			echo '<li class="prev  disabled"><a title="Ir a la pág. anterior" href="#">Anterior</a></li>';
		}
		
		/*first page*/
		if ($start == 1) { //se coloca el link sin numero de pagina para la pagina 1
			$start = 2;
			$show -= 1;
			$href = $url. $filter->getURL(array('page' => 1));
			echo ($page->current == 1) ? '<li class="active"><a href="#">1</a><li>':'<li>'.Html::link($href, '1').'</li>';
		} else{
			echo '<li>', Html::link($url, '1'), '</li>';
		}
		/*use ... on start */
		if ($start > 2):?><li><a href="#">...</a></li><?php endif;
		/*each page link*/
		for ($i = $start; $i <= $page->total && $i < ($start + $show); $i++): ?>
			<?php $href = $url. $filter->getURL(array('page' => $i));?>
			<?php echo $i == $page->current ? "<li class=\"active\"><a href='#'>$i</a><li>" : '<li>' . Html::link($href, $i) . '</li>'; ?>
		<?php endfor; 
		/*use ... on end */
		if ($page->total > $i): ?>
			<li><a href="#">...</a></li>
			<?php $href = $url. $filter->getURL(array('page' => $page->total));?>
			<?php echo '<li>', Html::link($href, $page->total), '</li>'; ?>
		<?php elseif ($i == $page->total): ?>
			<?php $href = $url. $filter->getURL(array('page' => $i));?>
			<?php echo '<li>', Html::linkAction($href, $i), '</li>'; ?>
		<?php endif; ?>
		<?php
		if ($page->next) {
			$href = $url. $filter->getURL(array('page' => $page->next));
			echo '<li class="prev">', Html::link($href, 'Siguiente', 'title="Ir a la pág. siguiente" class="nextprev"'), '</li>';
		} else {
			echo '<li class="prev disabled"><a title="Ir a la pág. siguiente" href="#">Siguiente</a></li>';
		}
		?>
	</ul>
</div>
<?php endif?>
