<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title><?php echo Config::get('config.application.name') ?></title>
        <?php
        Tag::css('backend/bootstrap.min');
        echo Html::includeCss();
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        
        ?>
    </head>
    <body>
        <?php View::partial('backend/cabecera_admin') ?>
        <div class="container">
            <div id="contenido" class="content">
                <?php View::content(); ?>
            </div>
            <?php View::partial('backend/pie') ?>
        </div>
        <?php echo Tag::js('bootstrap');?>
    </body>
</html>
