<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Autenticación - <?php echo Config::get('backend.app.nombre') ?></title>
        <?php
        Tag::css('backend/bootstrap.min');
        echo Html::includeCss();
        ?>
    </head>
    <body>
        <?php View::partial('backend/cabecera_app') ?>
        <div class="container">
            <div id="contenido" class="content span4 offset4">                    
                <?php View::content() ?>
                <?php echo Form::open(NULL, 'post', 'class="well"') ?>
                <h3>Autenticación</h3>
                <label for="login"><i class="icon-user"></i>
                    <?php echo Form::text('login', 'placeholder="Usuario"') ?></label>

                <label class="control-label" for="clave"><i class="icon-key"></i> 
                    <?php echo Form::pass('clave', 'placeholder="Contraseña"') ?></label>
                <div class="btn-group">
                    <button class=" btn btn-primary" type="submit"><i class="icon-signin"></i> Ingresar</button>
                    <?php if (Config::get('backend.app.registro')): ?>
                        <?php echo Html::link('registro', 'Registro <i class=" icon-folder-open"></i>', 'class="btn btn-info"') ?>
                    <?php endif; ?>
                </div>
                <?php echo Form::close() ?>
                <?php View::partial('backend/pie') ?>
            </div>
        </div>
        <?php
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        echo Tag::js('bootstrap/bootstrap');
        ?>
    </body>
</html>
