<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?php echo Config::get('backend.app.name') ?></title>
        <?php
        Tag::css('backend/bootstrap.min');
        echo Html::includeCss();
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        echo Tag::js('bootstrap/bootstrap');
        ?>
    </head>
    <body>
        <?php View::partial('backend/cabecera_app') ?>
        <div class="container">
            <div id="contenido" class="content span4 offset4">                    
                     <?php View::content() ?>
                     <?php echo Form::open(NULL, 'post', 'class="well"') ?>
                
                <div class="control-group">
                    <label class="control-label" for="login">Usuario </label>
                    <div class="controls">
                        <?php echo Form::text('login') ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="clave">Contrase&ntilde;a </label>
                    <div class="controls">
                        <?php echo Form::pass('clave'/* ,'autocomplete="off"' */) ?>
                    </div>
                </div>
                <?php if (Config::get('backend.app.registro')): ?>
                    <?php echo Html::link('registro', 'Registrate') ?>
                <?php endif; ?>
                <?php echo Form::submit('Ingresar', 'class="btn btn-primary"') ?>
                <?php echo Form::close() ?>
            </div>
        </div>
        <footer><?php echo Config::get('backend.app.footer') ?></footer>
    </div>
</body>
</html>
