<div class="page-header">
    <h1>Configurando <em><?php echo $config ?></em></h1>
</div>
<?php View::content() ?>
<div class="row">
    <div class="offset3 span6" >
        <?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
        <?php foreach ($values as $key => $val): ?>
            <fieldset>
                <legend><?php echo $key ?></legend>
                <?php foreach ($val as $name => $value): ?>
                    <div class="control-group">
                        <label class="control-label" for="config_name"><?php echo ucwords(strtr($name, '_-', '  ')); ?>: </label>
                        <div class="controls">
                            <?php if (in_array($value, array('On', 'Off'))): ?>
                                <?php echo Form::check("config.{$name}", 1, null, $value == 'On') ?>
                            <?php else: ?>
                                <?php echo Form::text("config.{$name}", null, $value) ?>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </fieldset>
        <?php endforeach; ?>

        <?php View::partial('backend/submit') ?>
        <?php echo Form::close() ?>
    </div>
</div>
