<div class="page-header">
    <h1>Configurando <em><?php echo $config?></em></h1>
</div>
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>

<?php foreach($values as $key => $val):?>
	<fieldset>
    <legend><?php echo $key?></legend>
    <?php foreach($val as $name => $value):?>
        <div class="control-group">
			<label class="control-label" for="config_name"><?php echo ucwords(strtr($name, '_-', '  ')); ?>: </label>
			<div class="controls">
				<?php echo Form::text("config.{$name}", null, $value) ?>
			</div>
		</div>
	<?php endforeach;?>
    </fieldset>
<?php endforeach;?>

<div class="form-actions">
    <?php echo Form::submit('Guardar Configuración', 'class="btn btn-primary"') ?>
        </div>
<?php echo Form::close() ?>
