<div class="page-header">
    <h1>Recursos del Sistema
        <?php echo Html::linkAction('escaner', 'Escanear Recursos por Agregar', 'class="btn btn-primary pull-right hidden-phone"') ?>
    </h1>
</div>
<?php View::content() ?>
<?php
View::partial('backend/barra_superior_listas', FALSE, array('texto' => 'Crear Recurso'));
$dt = new DataTable($recursos);
$dt->addHeaders('id', 'Modulo', 'Controlador', 'Acción', 'Descripción', 'Estado', 'Editar', 'Eliminar');
$dt->addFields('id', 'modulo', 'controlador', 'accion', 'descripcion');
$dt->link('admin/recursos/activar|admin/recursos/desactivar', '<span class="btn btn-success"><i class="icon-check icon-white" title="Activar"></i></span> | <span class="btn btn-danger"><i class="icon-ban-circle icon-white" title="Desactivar"></i></span>', 'activo');
$dt->link('admin/recursos/editar', '<span class="btn btn-warning"><i class="icon-edit icon-white" title="Activar"></i></span>');
$dt->linkConfirm('admin/recursos/eliminar', '<span class="btn btn-danger"><i class="icon-trash icon-white" title="Activar"></i></span>');
echo $dt->render('class="table table-bordered table-striped table-condensed"');
?>