app:
    name: Ashrey Backend
    logger: 1
    footer: Backend Kumbia PHP (C) 2015
    per_page: 10
    register: 1
    login: user

security:
    auth: \KBackend\Model\User
    acl: simple

database:
    backend:
        dsn: "mysql:host=localhost;dbname=backend;charset=utf8"
        username: root
        password: 
email:
    server: mail.server.com
    user: user@server.com
    password: yourpassword
    from: Ashrey Backend
    port: 25
    security: ssl
