{% extends 'default.phtml'%}
{%block title%}Create User{%endblock%}
{%block content%}
{%exec View::content %}
<div class="row">
    <div class="col-5 offset-3">
    	{%exec View::content%}
        {% autoescape off %}
            {%block result%}
                {%exec form.useDefaultBtn %}
                {{form}}
            {%endblock%}
        {% endautoescape %} 
    </div>
</div>
{%endblock%}