{% extends basetpl  %}
{%block title%}{{title}}{%endblock%}

{%block content%}
	{% if show_bar %}
		{% inline '_shared/scaffold_top.phtml'%}
	{%endif%}
	{%exec Flash::content %}
	{% autoescape off %}
		{%block result%}
			{%if result%}
				{%exec result->useCRUD %}
				{{result}}
			{%else%}
				<div class="alert alert-info">No hay resultados que mostrar</div>
			{%endif%}
		{%endblock%}
	{% endautoescape %}
{%endblock%}