<div class="page-header">
    <h1>Recursos por Agregar al Sistema</h1>
</div>
<?php View::content() ?>
<?php echo Form::open() ?>
<?php View::partial('backend/submit'); ?>
<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>Recurso</th>
            <th>Módulo</th>
            <th>Controlador</th>
            <th>Acción</th>
            <th>Descripción</th>
            <th>Activo</th>
            <th>Agregar</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($recursos->items as $index => $e) :++$index ?>
            <tr>
                <td><?php echo $e['recurso'] ?></td>
                <td><?php echo $e['modulo'] ?></td>
                <td><?php echo $e['controlador'] ?></td>
                <td><?php echo $e['accion'] ?></td>
                <td><?php echo Form::text("descripcion.$index", 'class="span6"') ?></td>
                <td><?php echo Form::check("activo.$index", 1) ?>            </td>
                <td><?php echo Form::check("check.$index", $index) ?>            </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php View::partial('paginators/bootstrap', false, array('page' => $recursos, 'url' => Router::get('controller_path') . '/escaner')); ?>
<?php echo Form::close(); ?>