{% extends 'default.phtml'%}
{%block title%}Acciones realizadas por <em>{{usuario.login}}</em>{%endblock%}
{%block content%}
	 {%exec View::content %}
<table class="t bordered condensed hover">
    <thead>
		<tr>
			<th>Fecha</th>
			<th>Tipo</th>
			<th>Acción</th>
			<th>IP</th>
		</tr>
	</thead>
	{%for item in result%}
    <tr>
		<td>{{item.date_at}}</td>
		<td>{{item.type}}</td>
		<td>{{item.action}}</td>
		<td>{{item.ip()}}</td>
    </tr>
    {%endfor%}
</table>
{%endblock%}