<div class="page-header">
    <h1>Menus del Sistema</h1>
</div>
<?php View::content() ?>
<?php
View::partial('backend/barra_superior_listas');
$dt = new DataTable($menus);
$dt->addHeaders('Texto a Mostrar', 'Menú Padre', 'Recurso al que Accede', 'URL', 'Posición');
$dt->addHeaders('Estado', 'Cambiar', 'Editar', 'Eliminar');
$dt->addFields('nombre', 'padre', 'recurso', 'url', 'posicion', 'activo: <span class="label label-important"><i class="icon-ban-circle icon-white" title="Activar"></i></span> | <span class="label label-success"><i class="icon-ok icon-white" title="Activar"></i></span>');
$dt->link('admin/menu/activar|admin/menu/desactivar',
          '<span class="btn btn-info"><i class="icon-check icon-white" title="Activar"></i></span>|<span class="btn btn-info"><i class="icon-off icon-white" title="Desactivar"></i></span>', 'activo');    
$dt->link('admin/menu/editar', '<span class="btn btn-warning"><i class="icon-edit icon-white" title="Editar"></i></span>');
$dt->linkConfirm('admin/menu/eliminar', '<span class="btn btn-danger"><i class="icon-trash icon-white" title="Eliminar"></i></span>');
echo $dt->render('class="table table-bordered table-hover table-condensed"');
?>
