<form action="" method="post" class="form-inline">
    <?php if (!empty($cond) && is_array($cond)): ?>
        <ul class="unstyled">
            <?php foreach ($cond as $key => $val): ?>
                <li><i class="icon-filter"></i>
                    <strong><?php echo $model->get_alias($val['col']); ?></strong>
                    <?php echo $rel[$val['rel']] ?>
                    <em><?php echo $val['val']; ?></em>
                    <button type="submit" class="btn btn-danger btn-mini" value="<?php echo $key ?>" name="remove">
                        <i class="icon-white icon-remove"></i></button></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <select name="filter[col]">
        <option value="">Seleccione...</option>
        <?php foreach ($col as $item): ?>

            <?php $key = $model->get_alias($item); ?>
            <option value="<?php echo $item ?>"><?php echo $key; ?></option>
        <?php endforeach; ?>		
    </select>
    <?php echo Form::select('filter.rel', $rel) ?>
    <input type="text" name="filter[val]"/>
    <button type="submit" class="btn btn-primary" value="add" name="add"><i class="icon-ok"></i></button>
    <button class="btn btn-danger" type="submit" value="clear" name="clear"><i class="icon-minus-sign"></i></button>
</form>