{%set login = AuthACL::isLogin() %}
<div class="navbar">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <i class="icon-cogs"></i>
    </button>
	<a class="navbar-brand">Administración</a>
	<div class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
		{%if login%}
			{%exec  Menu::render 1 %}
			<li>{%exec Html::link 'profile/logout', 'Salir' %}</li>
		{%else%}
			<li>{%exec Html::link 'profile', 'Entrar' %}</li>
		{%endif%}
		</ul>
	</div>
</div>
