{%for i in menu %}
	{%set submenu = i.sub | default:'' %}
	{%set class = i.class | default:'' %}
    {%if submenu %}
        <li class="{{class}} dropdown">
        {%buffer n%}{{i.name}}<b class="caret"></b>{%endbuffer%}
        {%exec Html::link '#', n,  'class="dropdown-toggle" data-toggle="dropdown"'%}
        <ul class="dropdown-menu">
        {%exec Menu::generate submenu %}
       </ul>
    {% else %}
        <li class="{{class}}">
        {%exec Html::link i.url, i.name %}
    {%endif%} 
    </li>
{%endfor%} 