<div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand">Área Admnistrativa</a>
            <div class="nav-collapse">
                <?php echo Menu::render(1) ?>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <?php eh(\KBackend\Libs\AuthACL::get('login')) ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?php echo Html::link('index/logout', 'Salir') ?></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
