{% extends 'default.phtml'%}
{%block title%}Privilegios para <em>{{rol.role}}</em>{%endblock%}
{%block content%}
    {%exec View::content %}
    {% if result %}
        {%exec Form::open 'access/assign' %}
        {%inline '_shared/submit.phtml' %}
        {%exec  Form::hidden "rol", FALSE, rol.id %}
       {% autoescape off %} {{result}}{% endautoescape %} 
    {%else%}
        <h2>No hay ningún registro</h2>
    {%endif%}
{%endblock%}