<div class="page-header">
    <h1>Crear Usuario</h1>
</div>
<div class="row">
    <div class="offset3 span6" >
        <div id="res-form-ajax"><?php View::content() ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal') ?>
        <?php echo Form::hidden('user.id') ?>
        <div class="control-group">
            <label class="control-label" for="usuario_login">Nombre de Usuario</label>
            <div class="controls">
                <?php echo Form::text('user.login') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_clave">Contraseña</label>
            <div class="controls">
                <?php echo Form::pass('user.password') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_clave2">Repita  Contraseña</label>
            <div class="controls">
                <?php echo Form::pass('user.clave2') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_email">Correo Electronico</label>
            <div class="controls">
                <?php echo Form::text('user.email') ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="usuario_roles_id">Roles del Usuario</label>
            <div class="controls">
				<?php echo Form::dbSelect('user.role_id', 'role', array('\KBackend\Model\Role','find')) ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="user_enable">Activo : </label>
            <div class="controls">
                <?php echo Form::select('user.enable', array('1' => 'Si', '0' => 'No')) ?>
            </div>
        </div>
        <?php View::partial('backend/submit');?>

        <?php echo Form::close() ?>
    </div>
</div>
