<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio - <?php echo Config::get('backend.app.nombre') ?></title>
        <?php
        Tag::css('backend/bootstrap.min');
        echo Html::includeCss();
        ?>
    </head>
    <body>
        <?php View::partial('backend/cabecera_app') ?>
        <div class="container">
            <div id="contenido" class="content">
                <?php View::content() ?>
            </div>
            <?php View::partial('backend/pie') ?>
        </div>

        <?php
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        ?>
    </body>
</html>
