<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio - <?php echo Config::get('backend.app.nombre') ?></title>
        <?php
        Tag::css('backend/bootstrap.min');
        echo Html::includeCss();
        ?>
    </head>
    <body>
        <div id='cabecera' class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <?php echo Html::link('', Config::get('backend.app.nombre'), 'class="brand"') ?>
            <div class="nav-collapse pull-right">
                <ul class="nav">
                    <li><?php echo Html::link('user/', 'Administración') ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>
        <div class="container">
            <div id="contenido" class="content">
                <?php View::content() ?>
            </div>
            <?php View::partial('backend/pie') ?>
        </div>

        <?php
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        ?>
    </body>
</html>
