<!DOCTYPE html>
<html lang="es">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{%exec Config::get 'backend.app.nombre'%}</title>
        {%block css %}
            {%css style%}
        {%endblock%}
    </head>
    <body>
        {% inline  '_shared/partials/backend/header.phtml' %}
        <div class="container">
            <div id="contenido" class="content">
                {% block content%}{%endblock%}
            </div>
        </div>
    </body>
    {%js 'zepto.kumbiaphp' %}
    {%js 'bootstrap' %}
</html>
