<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Inicio - <?php echo Config::get('backend.app.nombre') ?></title>
        <?php
        Tag::css('bootstrap.min');
        echo Html::includeCss();
        ?>
    </head>
    <body>
        <div id='cabecera' class="navbar">
			<div class="container">
				<?php echo Html::link('', Config::get('backend.app.nombre'), 'class="navbar-brand"') ?>
				<?php echo Form::open("user", 'post', 'class="navbar-form navbar-right"');?>
					<div class="form-group">
					  <input type="text" placeholder="usuario" class="form-control" name="login">
					</div>
					<div class="form-group">
					  <input type="password" placeholder="Password" class="form-control" name="clave">
					</div>
					<button type="submit" class="btn btn-default">Entrar</button>
				</form>
			</div>
		</div>
        <div class="container">
			<?php View::content() ?>
        </div>
        <?php View::partial('backend/pie');?>
        <?php echo Tag::js('zepto.kumbiaphp');?>
    </body>
</html>
