<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset='<?php echo APP_CHARSET ?>' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Autenticación - <?php echo Config::get('backend.app.nombre') ?></title>
        <?php
        Tag::css('bootstrap.min');
        echo Html::includeCss();
        ?>
    </head>
    <body>
		<div class="container">               
                <?php View::content() ?>
           <div class="col-md-4 col-md-offset-4">
                <?php echo Form::open(NULL, 'post', 'class="well"') ?>
				<h2 class="form-signin-heading">Autenticación</h2>
				<div class="form-group">
					<label for="login"><i class="icon-user"></i></label>
                    <?php echo Form::text('login', 'placeholder="Usuario" class="form-control"') ?>
				</div>
				
				<div class="form-group">
                <label class="control-label" for="clave"><i class="icon-key"></i> </label>
                    <?php echo Form::pass('clave', 'placeholder="Contraseña" class="form-control"') ?>
                 </div>
                <div class="btn-group">
                    <button class="btn-lg btn btn-primary" type="submit"><i class="icon-signin"></i> Ingresar</button>
                    <?php if (Config::get('backend.app.registro')): ?>
                        <?php echo Html::link('registro', 'Registro <i class=" icon-folder-open"></i>', 'class="btn btn-info"') ?>
                    <?php endif; ?>
                </div>
                <?php echo Form::close() ?>
            </div>
        </div>
        <?php
        echo Tag::js('jquery/jquery.min');
        echo Tag::js('jquery/jquery.kumbiaphp');
        echo Tag::js('bootstrap/bootstrap');
        ?>
    </body>
</html>
