<div class="page-header">
    <h1>Auditorias del Sistema</h1>
</div>
<?php View::content() ?>
<h3>Usuarios del Sistema</h3>
<?php
    $dt = new DataTable($usuarios);
    $dt->addHeaders('id', 'Login', 'Nombres');
    $dt->addHeaders('Acciones');
    $dt->addHeaders('Examinar');
    $dt->addFields('id', 'login', 'nombres', 'num_acciones');
    $dt->link('admin/auditorias/usuario', '<span class="btn btn-primary"><i class="icon-eye-open icon-white"></i></span>');
    echo $dt->render('class="table table-bordered table-hover table-condensed"');
?>
