<div class="page-header">
    <h1>Configuración de Perfil</h1>
</div>       
<?php View::content() ?>
<ul class="nav nav-tabs">
    <li class="active"><a href="#datos-personales" data-toggle="tab">Datos Personales</a></li>
    <li><a href="#clave" data-toggle="tab">Contraseña</a></li>
</ul>
<div class="tab-content">
    <div id="datos-personales" class="tab-pane active">
        <?php echo Ajax::form('res-datos-personales', NULL, 'form-horizontal') //Form::open() ?>
        <fieldset>
            <legend>Configurar Datos Personales</legend>
            <div class="control-group">                
                <label class="control-label" for="usuario_email">Correo Electronico </label>
                <div class="controls">
                    <?php echo Form::text('usuario1.email') ?>
                </div>
            </div>
            <?php View::partial('backend/submit') ?>
        </fieldset>
        <?php echo Form::close() ?>
    </div>
    <div id="clave" class="tab-pane">
        <?php echo Ajax::form('res-clave', NULL, 'form-horizontal')//Form::open() ?>
        <fieldset>
            <legend>Cambiar Contrase&ntilde;a</legend>
            <br/>
            <div id="res-clave"></div>
            <div class="control-group">
                <label class="control-label" for="usuario_clave">Contraseña Actual</label>
                <div class="controls">
                    <?php echo Form::pass('usuario2.clave_actual') ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="usuario_clave">Nueva Contraseña</label>
                <div class="controls">
                    <?php echo Form::pass('usuario2.nueva_clave') ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="usuario_clave2">Repetir Contraseña</label>
                <div class="controls">
                    <?php echo Form::pass('usuario2.nueva_clave2') ?>
                </div>
            </div>
            <?php View::partial('backend/submit') ?>
        </fieldset>
        <?php echo Form::close() ?>
    </div>
</div>