<?php if ($result) : ?>
<div class="page-header">
    <h1><?php echo $result->login ?></h1>
</div>

<div class="row">
  <div class="span4 offset4">
    <dl class="dl-horizontal">
        <?php foreach ($result->fields as $field):?>
        
            <dt><?php echo $result->alias[$field] ?>:</dt>
            <?php 
            /*permite llamar a las claves foraneas*/
            if(isset($field[3]) && strripos($field, '_id', -3)){
                $method = substr($field,0, -3);
                $t = $result->$method;
                $c = $t->non_primary[0];
                $value =  h($t->$c);
            }else{
                $value = $result->$field;
            }?>
            <dd> <?php eh($value) ?></dd>
        <?php endforeach ?>
    </dl>
   </div>
<?php else : ?>
    <?php header("HTTP/1.0 404 Not Found") ?>
	<div class="page-header">
    <h1>No existe</h1>
    </div>
    <div class="row">

  <div class="span4 offset4">
	<div class="btn-group">
		<?php echo Html::LinkAction('crear', 'Crear <i class="icon-plus icon-white"></i>',' class="btn btn-primary"')?>
		<?php echo Html::LinkAction('', 'Listar  <i class="icon-list icon-white"></i>',' class="btn btn-info"')?>
    </div>
   </div></div>
<?php endif ?>
</div>
