{% extends 'default.phtml'%}
{%block title%}Recuperar contraseña{%endblock%}
{%block content%}
    <div class="col-8 offset-2">
        {%exec Flash::content %}
        {%if show %}
            {%exec Form::open '', 'post', 'class="horizontal"' %}
        	<div class="form-group">
        		<label for="forget" class="col-4 control">Nombre de Usuario o correo</label>
        		<div class="col-8">
        			{%exec Form::text 'forget', 'class="control"' %}
        		</div>
        	</div>
        	{%inline '_shared/submit.phtml' %}
            {%exec Form::close %}
        {%endif%}
    </div>
{%endblock%}
