<div class="page-header">
    <h1>Crear una Cuenta</h1>
</div>
<?php View::content(); ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('user.id') ?>
<div class="form-group">
    <label for="user_login" class="col-sm-2 control-label">Nombre de Usuario</label>
    <div class="col-sm-8">
        <?php echo Form::text('user.login', 'class="form-control"') ?>
    </div>
</div>
<div class="form-group">
    <label for="user_clave" class="col-sm-2 control-label">Contraseña</label>
    <div class="col-sm-8">
        <?php echo Form::pass('user.password', 'class="form-control"') ?>
    </div>
</div>
<div class="form-group">
    <label for="user_clave2" class="col-sm-2 control-label">Repita Contraseña</label>
    <div class="col-sm-8">
        <?php echo Form::pass('user.clave2', 'class="form-control"') ?>
    </div>
</div>
<div class="form-group">
    <label for="user_email" class="col-sm-2 control-label">Correo Electrónico</label>
    <div class="col-sm-8">
        <?php echo Form::text('user.email', 'class="form-control"') ?>
    </div>
</div>
<?php View::partial('backend/submit') ?>
<?php echo Form::close() ?>
