{% extends 'default.phtml'%}
{%block title%}Crear una Cuenta{%endblock%}
{%block content%}
	<div class="col-8 offset-2">
	{%exec Flash::content %}
	{%exec Form::open '', 'post', 'class="horizontal"' %}
	<div class="form-group">
		<label for="user_login" class="col-4 control">Nombre de Usuario</label>
		<div class="col-8">
			{%exec Form::text 'user.login', 'class="control" required maxlength="20"' %}
		</div>
	</div>
	<div class="form-group">
		<label for="user_password" class="col-4 control">Contraseña</label>
		<div class="col-8">
			{% exec  Form::pass 'user.password', 'class="control" required'  %}
		</div>
	</div>
	<div class="form-group">
		<label for="user_password2" class="col-4 control">Repita Contraseña</label>
		<div class="col-8">
			{% exec  Form::pass 'user.password2', 'class="control" required'  %}
		</div>
	</div>
	<div class="form-group">
		<label for="user_email" class="col-4 control">Correo Electrónico</label>
		<div class="col-8">
			{% exec  Form::email 'user.email', 'class="control" required'  %}
		</div>
	</div>
	<input type="text" name="email" style="display:none"/>
	{%inline '_shared/form/submit.phtml' %}
	</div>
{%endblock%}