<!DOCTYPE html>
<html lang="es">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8"> 
        <title>{%exec Config::get 'backend.app.name'%}</title>
        {%block css %}
            {%css style%}
        {%endblock%}
    </head>
    <body>
        {%block body%}
        {% inline  '_shared/header.phtml' %}
        <div class="container">
            <div id="contenido" class="content">
            {%block header%}
                <header>
                    <h1>{% block title%}{%endblock%}</h1>
                </header>
            {%endblock%}
            {% block content%}

            {%endblock%}
            </div>
        </div>
        {%endblock%}
    </body>
    {%js 'zepto.kumbiaphp' %}
    {%js 'bootstrap' %}
</html>
