{% extends 'default.phtml'%}
{%block body%}
	<div class="container">               
       <div class="col-4 offset-4">
            {% exec Form::open '', 'post', 'class="jumbotron"' %}
			<h2>Autenticación</h2>
            {%exec Flash::content%}
			<div class="form-group">
				<label for="user"><i class="fa fa-group"></i></label>
                {% exec Form::text 'login.user', 'placeholder="Usuario" class="control"' %}
			</div>

			<div class="form-group">
            <label class="control-label" for="password"><i class="fa fa-key"></i> </label>
                {% exec  Form::pass 'login.password', 'placeholder="Contraseña" class="control"' %}
             </div>

            <div class="btn-group">
                <button class="btn btn-primary" type="submit"><i class="fa fa-sign-in"></i> Ingresar</button>
                {% buffer reg%}{%exec Config::get 'backend.app.register'%}{% endbuffer %}
                {% if reg %}
                    {%exec Html::link 'registro', 'Registro <i class="fa fa-book"></i>', 'class="btn btn-info"' %}
                {% endif %}
            </div>
            {%exec Html::link 'register/forget', 'Olvidé mi contraseña' %}
            {% exec Form::close%}
        </div>
    </div>
{%endblock%}